
CREATE OR REPLACE VIEW capim.master_table as (
with first_subscription as (
  SELECT DISTINCT 
  CLINIC_ID, 
  MIN(SUBSCRIPTION_START_DATE) AS FIRST_SUBSCRIPTION_START_DATE
  FROM capim.subscriptions_table
  WHERE CHECKOUT_STATUS in ('open', 'complete')
  GROUP BY CLINIC_ID

) 

, last_subscription as (
  SELECT DISTINCT 
  CLINIC_ID, 
  SUBSCRIPTION_STATUS,
  CASE WHEN SUBSCRIPTION_STATUS = 'canceled' then true else false end as IS_CHURN,
  MAX(SUBSCRIPTION_START_DATE) AS LAST_SUBSCRIPTION_START_DATE,
  FROM capim.subscriptions_table
  WHERE CHECKOUT_STATUS in ('open', 'complete')
  GROUP BY CLINIC_ID, SUBSCRIPTION_STATUS, IS_CHURN
) 

, dau as (
  SELECT 
  CLINIC_ID, 
  sum(ACTIVE_FINANCE) as ACTIVE_FINANCE,
  sum(ACTIVE_PATIENT) as ACTIVE_PATIENT,
  sum(ACTIVE_SETUP) as ACTIVE_SETUP,
  sum(ACTIVE_SCHEDULE) as ACTIVE_SCHEDULE,
  SUM(ACTIVE_USER) AS ACTIVE_USER,
  FROM (
    SELECT 
    CLINIC_ID,
    EXTRACT(DATE FROM ACTIVITY_AT) as DATE,
    EXTRACT(DAYOFWEEK FROM ACTIVITY_AT) as DAY_OF_WEEK,
    MAX(CASE WHEN module = 'finance' THEN 1 else 0 end) as ACTIVE_FINANCE,
    MAX(CASE WHEN module = 'patient' THEN 1 else 0 end) as ACTIVE_PATIENT,
    MAX(CASE WHEN module = 'setup' THEN 1 else 0 end ) AS ACTIVE_SETUP,
    MAX(CASE WHEN module = 'schedule' THEN 1 else 0 end) as ACTIVE_SCHEDULE,
    MAX(CASE WHEN module IS NOT NULL THEN 1 else 0 end) as ACTIVE_USER
  FROM `capim-404203.capim.activity_table` 
  GROUP BY 1,2,3
  ORDER BY DATE DESC)
  GROUP BY 1
)

, interactions as (
  SELECT 
  a.CLINIC_ID,
  sum(CASE WHEN module = 'finance' THEN 1 else 0 end) as ACTIVE_FINANCE,
  sum(CASE WHEN module = 'patient' THEN 1 else 0 end) as ACTIVE_PATIENT,
  sum(CASE WHEN module = 'setup' THEN 1 else 0 end ) AS ACTIVE_SETUP,
  sum(CASE WHEN module = 'schedule' THEN 1 else 0 end) as ACTIVE_SCHEDULE,
  sum(CASE WHEN module IS NOT NULL THEN 1 else 0 end) as ACTIVE_USER
  FROM `capim-404203.capim.activity_table` a
  GROUP BY 1
)


, creditation_time as (
SELECT 
CLINIC_ID,
DATE_DIFF(DATE(ACCREDITATION_REQUESTED_AT), DATE(CLINIC_CREATED_AT), DAY) AS REQUEST_TIME,
DATE_DIFF(DATE(ACCREDITATION_REQUESTED_AT), DATE(CLINIC_CREATED_AT), DAY)
 - (DATE_DIFF(DATE(ACCREDITATION_REQUESTED_AT),DATE(CLINIC_CREATED_AT), WEEK) * 2) AS REQUEST_TIME_BUSINESS_DAYS,
DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(ACCREDITATION_REQUESTED_AT), DAY) as RESPONSE_TIME_DAYS,
DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)), DATE(ACCREDITATION_REQUESTED_AT), DAY)
 - (DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(ACCREDITATION_REQUESTED_AT), WEEK) * 2) AS RESPONSE_TIME_BUSINESS_DAYS,
DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(CLINIC_CREATED_AT), DAY) as PROCESS_TIME_DAYS,
DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)), DATE(CLINIC_CREATED_AT), DAY)
 - (DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(CLINIC_CREATED_AT), WEEK) * 2) AS PROCESS_TIME_BUSINESS_DAYS,
 FROM `capim-404203.capim.clinics_table`)


SELECT c.*,
 fs.FIRST_SUBSCRIPTION_START_DATE,
 ls.LAST_SUBSCRIPTION_START_DATE,
 ls.SUBSCRIPTION_STATUS,
 ls.IS_CHURN,
 CASE WHEN d.ACTIVE_FINANCE IS NULL THEN 0 ELSE d.ACTIVE_FINANCE END AS ACTIVE_FINANCE ,
 CASE WHEN d.ACTIVE_PATIENT IS NULL THEN 0 ELSE d.ACTIVE_PATIENT END AS ACTIVE_PATIENT ,
 CASE WHEN d.ACTIVE_SETUP IS NULL THEN 0 ELSE d.ACTIVE_SETUP END AS ACTIVE_SETUP ,
 CASE WHEN d.ACTIVE_SCHEDULE IS NULL THEN 0 ELSE d.ACTIVE_SCHEDULE END AS ACTIVE_SCHEDULE ,
 CASE WHEN d.ACTIVE_USER IS NULL THEN 0 ELSE d.ACTIVE_USER END AS ACTIVE_USER ,
 CASE WHEN i.ACTIVE_USER IS NULL then 0 ELSE i.ACTIVE_USER END AS INTERACTIONS,
 CASE WHEN fs.FIRST_SUBSCRIPTION_START_DATE is not null THEN  True else False end  as IS_CONVERTED,
 CASE WHEN p.PREDICTION_IS_CONVERTED is null then 0 else p.PREDICTION_IS_CONVERTED end as PREDICTION_IS_CONVERTED,
 CASE WHEN p.PREDICTION_CONVERTED_CHANCE is null then 0 else p.PREDICTION_CONVERTED_CHANCE end as PREDICTION_CONVERTED_CHANCE,
 case when ct.REQUEST_TIME < 0 then 0 else ct.REQUEST_TIME end as REQUEST_TIME, # Casos de redes homolagas aprovadas antes do cadastro
 case when ct.REQUEST_TIME_BUSINESS_DAYS < 0 then 0 else ct.REQUEST_TIME_BUSINESS_DAYS end as REQUEST_TIME_BUSINESS_DAYS,    # Casos de redes homolagas aprovadas antes do cadastro
 ct.RESPONSE_TIME_DAYS,
 ct.RESPONSE_TIME_BUSINESS_DAYS,
 ct.PROCESS_TIME_DAYS,
 ct.PROCESS_TIME_BUSINESS_DAYS,
 case when c.TRIAL_END_DATE >= '2023-09-30' then True else False end as IS_IN_TRIAL
from capim.clinics_table c
left join  first_subscription fs ON fs.CLINIC_ID = c.CLINIC_ID
left join  last_subscription ls ON ls.CLINIC_ID = c.CLINIC_ID
left join dau d ON d.CLINIC_ID = c.CLINIC_ID
left join capim.prediction_converted p ON p.CLINIC_ID = c.CLINIC_ID
left join creditation_time ct ON ct.CLINIC_ID = c.CLINIC_ID
left join interactions i on i.CLINIC_ID = c.CLINIC_ID
where TRIAL_START_DATE is not null
)

