

SELECT *,
--EXTRACT(HOUR FROM CLINIC_CREATED_AT -  ACCREDITATION_REQUESTED_AT)/24 AS REQUEST_TIME_HOURS,

--EXTRACT(HOUR FROM ACCREDITATION_REQUESTED_AT - COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT))  as RESPONSE_TIME_HOURS

DATE_DIFF(DATE(ACCREDITATION_REQUESTED_AT), DATE(CLINIC_CREATED_AT), DAY) AS REQUEST_TIME,
DATE_DIFF(DATE(ACCREDITATION_REQUESTED_AT), DATE(CLINIC_CREATED_AT), DAY)
 - (DATE_DIFF(DATE(ACCREDITATION_REQUESTED_AT),DATE(CLINIC_CREATED_AT), WEEK) * 2) AS REQUEST_TIME_BUSINESS_DAYS,


DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(ACCREDITATION_REQUESTED_AT), DAY) as RESPONSE_TIME_DAYS,
DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)), DATE(ACCREDITATION_REQUESTED_AT), DAY)
 - (DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(ACCREDITATION_REQUESTED_AT), WEEK) * 2) AS RESPONSE_TIME_BUSINESS_DAYS,

DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(CLINIC_CREATED_AT), DAY) as PROCESS_TIME_DAYS,
DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)), DATE(CLINIC_CREATED_AT), DAY)
 - (DATE_DIFF(DATE(COALESCE(ACCREDITATION_APPROVED_AT,ACCREDITATION_REJECTED_AT)),DATE(CLINIC_CREATED_AT), WEEK) * 2) AS PROCESS_TIME_BUSINESS_DAYS,

 FROM `capim-404203.capim.clinics_table` where HAS_ASKED_FOR_ACCREDITATION is true