with interactions as (
SELECT 
a.CLINIC_ID,
sum(CASE WHEN module = 'finance' THEN 1 else 0 end) as ACTIVE_FINANCE,
sum(CASE WHEN module = 'patient' THEN 1 else 0 end) as ACTIVE_PATIENT,
sum(CASE WHEN module = 'setup' THEN 1 else 0 end ) AS ACTIVE_SETUP,
sum(CASE WHEN module = 'schedule' THEN 1 else 0 end) as ACTIVE_SCHEDULE,
sum(CASE WHEN module IS NOT NULL THEN 1 else 0 end) as ACTIVE_USER
FROM `capim-404203.capim.activity_table` a
GROUP BY 1
)

, first_subscription as (
SELECT DISTINCT 
CLINIC_ID, 
MIN(SUBSCRIPTION_START_DATE) AS FIRST_SUBSCRIPTION_START_DATE
FROM capim.subscriptions_table
WHERE CHECKOUT_STATUS in ('open', 'complete')
GROUP BY CLINIC_ID

), 

subscription_status as (
SELECT c.*,
 fs.FIRST_SUBSCRIPTION_START_DATE,
 CASE WHEN fs.FIRST_SUBSCRIPTION_START_DATE is not null THEN  True else False end  as IS_CONVERTED,
from capim.clinics_table c
left join  first_subscription fs ON fs.CLINIC_ID = c.CLINIC_ID
where TRIAL_START_DATE is not null
)


SELECT 
c.CLINIC_ID,
c.TRIAL_DURATION,
c.IS_CHAIN_CLINIC,
s.IS_CONVERTED,
SUM(d.ACTIVE_FINANCE)/C.TRIAL_DURATION as ACTIVE_FINANCE_DAYS,
SUM(d.ACTIVE_PATIENT)/C.TRIAL_DURATION as ACTIVE_PATIENT_DAYS,
SUM(d.ACTIVE_SETUP)/C.TRIAL_DURATION as ACTIVE_SETUP_DAYS,
SUM(d.ACTIVE_SCHEDULE)/C.TRIAL_DURATION as ACTIVE_SCHEDULE_DAYS,
SUM(d.ACTIVE_USER)/C.TRIAL_DURATION as ACTIVE_USER_DAYS,
SUM(d.ACTIVE_USER) AS ACTIVE_USER_DAYS_RAW

FROM capim.clinics_table c
LEFT JOIN interactions d on d.CLINIC_ID = c.CLINIC_ID
LEFT JOIN subscription_status s on s.CLINIC_ID = c.CLINIC_ID
WHERE c.TRIAL_DURATION > 0
GROUP BY 1,2,3,4
HAVING IS_CHAIN_CLINIC is False