
with  first_subscription as (
SELECT DISTINCT 
CLINIC_ID, 
MIN(SUBSCRIPTION_START_DATE) AS FIRST_SUBSCRIPTION_START_DATE
FROM capim.subscriptions_table
WHERE CHECKOUT_STATUS in ('open', 'complete')
GROUP BY CLINIC_ID

)

, subscription_status as (
SELECT c.*,
 fs.FIRST_SUBSCRIPTION_START_DATE,
 CASE WHEN fs.FIRST_SUBSCRIPTION_START_DATE is not null THEN  True else False end  as IS_CONVERTED,
from capim.clinics_table c
left join  first_subscription fs ON fs.CLINIC_ID = c.CLINIC_ID
where TRIAL_START_DATE is not null
)



SELECT 
FEATURE,
IS_CONVERTED,
SUM(CASE WHEN ACTIVE_USER >=1 THEN 1 ELSE 0 END) AS days_1,
SUM(CASE WHEN ACTIVE_USER >=2 THEN 1 ELSE 0 END) AS days_2,
SUM(CASE WHEN ACTIVE_USER >=3 THEN 1 ELSE 0 END) AS days_3,
SUM(CASE WHEN ACTIVE_USER >=4 THEN 1 ELSE 0 END) AS days_4,
SUM(CASE WHEN ACTIVE_USER >=5 THEN 1 ELSE 0 END) AS days_5,
SUM(CASE WHEN ACTIVE_USER >=6 THEN 1 ELSE 0 END) AS days_6,
SUM(CASE WHEN ACTIVE_USER >=7 THEN 1 ELSE 0 END) AS days_7,

FROM (
SELECT
CLINIC_ID,
FEATURE,
IS_CONVERTED,
SUM(ACTIVE_USER) AS ACTIVE_USER
FROM (  
SELECT 
a.CLINIC_ID,
s.IS_CONVERTED,
EXTRACT(DATE FROM ACTIVITY_AT) as DATE,
EXTRACT(DAYOFWEEK FROM ACTIVITY_AT) as DAY_OF_WEEK,
a.FEATURE,
MAX(CASE WHEN module IS NOT NULL THEN 1 else 0 end) as ACTIVE_USER
FROM `capim-404203.capim.activity_table` a
LEFT JOIN capim.clinics_table c on c.CLINIC_ID = a.CLINIC_ID
LEFT JOIN subscription_status s on s.CLINIC_ID = a.CLINIC_ID
WHERE c.TRIAL_DURATION > 0
GROUP BY 1,2,3,4,5
ORDER BY DATE DESC
)
GROUP BY 1,2,3)
GROUP BY 1,2