select 

SUM(TICKET_MONTH)/COUNT(CLINIC_ID) as TICKET_MÉDIO
FROM (
SELECT 
CLINIC_ID,
BILLING_INTERVAL_IN_MONTHS,
FIRST_PAYMENT_AMOUNT, 
FIRST_PAYMENT_AMOUNT/ BILLING_INTERVAL_IN_MONTHS AS TICKET_MONTH  
FROM capim.subscriptions_table where CHECKOUT_STATUS = 'complete' )
